/**
 * Open Task Board (OTB) - Common Definitions
 * Definitions that are common to both the frontend and backend.
 */
const OTB_ROLES = {
    admin: "Administrator",
    project_manager: "Project Manager",
    employee: "Employee",
    associate: "Associate",
    member: "Member",
    guest: "Guest",
};

const OTB_JOB_TITLES = {
    account_manager: "Account Manager",
    administrator: "Administrator",
    analyst: "Analyst",
    backend_developer: "Backend Developer",
    business_analyst: "Business Analyst",
    ceo: "Chief Executive Officer",
    cfo: "Chief Financial Officer",
    coo: "Chief Operating Officer",
    consultant: "Consultant",
    coordinator: "Coordinator",
    customer_success: "Customer Success Manager",
    data_analyst: "Data Analyst",
    data_scientist: "Data Scientist",
    database_administrator: "Database Administrator",
    designer: "Designer",
    devops_engineer: "DevOps Engineer",
    director: "Director",
    engineer: "Engineer",
    executive_assistant: "Executive Assistant",
    frontend_developer: "Frontend Developer",
    founder: "Founder",
    fullstack_developer: "Full Stack Developer",
    hr_manager: "HR Manager",
    intern: "Intern",
    marketing_manager: "Marketing Manager",
    mobile_developer: "Mobile Developer",
    network_engineer: "Network Engineer",
    office_manager: "Office Manager",
    operations_manager: "Operations Manager",
    owner: "Owner",
    product_manager: "Product Manager",
    project_manager: "Project Manager",
    qa_engineer: "QA Engineer",
    recruiter: "Recruiter",
    researcher: "Researcher",
    sales_manager: "Sales Manager",
    scrum_master: "Scrum Master",
    security_engineer: "Security Engineer",
    software_architect: "Software Architect",
    software_engineer: "Software Engineer",
    specialist: "Specialist",
    support_engineer: "Support Engineer",
    system_administrator: "System Administrator",
    technical_writer: "Technical Writer",
    tester: "Tester",
    trainer: "Trainer",
    ui_designer: "UI Designer",
    ux_designer: "UX Designer",
    vp_engineering: "VP of Engineering",
    other: "Other"
};

const OTB_COUNTRIES = {
    afghanistan: "Afghanistan",
    albania: "Albania",
    algeria: "Algeria",
    andorra: "Andorra",
    angola: "Angola",
    antigua_and_barbuda: "Antigua and Barbuda",
    argentina: "Argentina",
    armenia: "Armenia",
    australia: "Australia",
    austria: "Austria",
    azerbaijan: "Azerbaijan",
    bahamas: "Bahamas",
    bahrain: "Bahrain",
    bangladesh: "Bangladesh",
    barbados: "Barbados",
    belarus: "Belarus",
    belgium: "Belgium",
    belize: "Belize",
    benin: "Benin",
    bhutan: "Bhutan",
    bolivia: "Bolivia",
    bosnia_and_herzegovina: "Bosnia and Herzegovina",
    botswana: "Botswana",
    brazil: "Brazil",
    brunei: "Brunei",
    bulgaria: "Bulgaria",
    burkina_faso: "Burkina Faso",
    burundi: "Burundi",
    cambodia: "Cambodia",
    cameroon: "Cameroon",
    canada: "Canada",
    cape_verde: "Cape Verde",
    central_african_republic: "Central African Republic",
    chad: "Chad",
    chile: "Chile",
    china: "China",
    colombia: "Colombia",
    comoros: "Comoros",
    congo: "Congo",
    costa_rica: "Costa Rica",
    croatia: "Croatia",
    cuba: "Cuba",
    cyprus: "Cyprus",
    czech_republic: "Czech Republic",
    denmark: "Denmark",
    djibouti: "Djibouti",
    dominica: "Dominica",
    dominican_republic: "Dominican Republic",
    east_timor: "East Timor",
    ecuador: "Ecuador",
    egypt: "Egypt",
    el_salvador: "El Salvador",
    equatorial_guinea: "Equatorial Guinea",
    eritrea: "Eritrea",
    estonia: "Estonia",
    eswatini: "Eswatini",
    ethiopia: "Ethiopia",
    fiji: "Fiji",
    finland: "Finland",
    france: "France",
    gabon: "Gabon",
    gambia: "Gambia",
    georgia: "Georgia",
    germany: "Germany",
    ghana: "Ghana",
    greece: "Greece",
    grenada: "Grenada",
    guatemala: "Guatemala",
    guinea: "Guinea",
    guinea_bissau: "Guinea-Bissau",
    guyana: "Guyana",
    haiti: "Haiti",
    honduras: "Honduras",
    hungary: "Hungary",
    iceland: "Iceland",
    india: "India",
    indonesia: "Indonesia",
    iran: "Iran",
    iraq: "Iraq",
    ireland: "Ireland",
    israel: "Israel",
    italy: "Italy",
    jamaica: "Jamaica",
    japan: "Japan",
    jordan: "Jordan",
    kazakhstan: "Kazakhstan",
    kenya: "Kenya",
    kiribati: "Kiribati",
    korea_north: "North Korea",
    korea_south: "South Korea",
    kosovo: "Kosovo",
    kuwait: "Kuwait",
    kyrgyzstan: "Kyrgyzstan",
    laos: "Laos",
    latvia: "Latvia",
    lebanon: "Lebanon",
    lesotho: "Lesotho",
    liberia: "Liberia",
    libya: "Libya",
    liechtenstein: "Liechtenstein",
    lithuania: "Lithuania",
    luxembourg: "Luxembourg",
    madagascar: "Madagascar",
    malawi: "Malawi",
    malaysia: "Malaysia",
    maldives: "Maldives",
    mali: "Mali",
    malta: "Malta",
    marshall_islands: "Marshall Islands",
    mauritania: "Mauritania",
    mauritius: "Mauritius",
    mexico: "Mexico",
    micronesia: "Micronesia",
    moldova: "Moldova",
    monaco: "Monaco",
    mongolia: "Mongolia",
    montenegro: "Montenegro",
    morocco: "Morocco",
    mozambique: "Mozambique",
    myanmar: "Myanmar",
    namibia: "Namibia",
    nauru: "Nauru",
    nepal: "Nepal",
    netherlands: "Netherlands",
    new_zealand: "New Zealand",
    nicaragua: "Nicaragua",
    niger: "Niger",
    nigeria: "Nigeria",
    north_macedonia: "North Macedonia",
    norway: "Norway",
    oman: "Oman",
    pakistan: "Pakistan",
    palau: "Palau",
    palestine: "Palestine",
    panama: "Panama",
    papua_new_guinea: "Papua New Guinea",
    paraguay: "Paraguay",
    peru: "Peru",
    philippines: "Philippines",
    poland: "Poland",
    portugal: "Portugal",
    qatar: "Qatar",
    romania: "Romania",
    russia: "Russia",
    rwanda: "Rwanda",
    saint_kitts_and_nevis: "Saint Kitts and Nevis",
    saint_lucia: "Saint Lucia",
    saint_vincent_and_the_grenadines: "Saint Vincent and the Grenadines",
    samoa: "Samoa",
    san_marino: "San Marino",
    sao_tome_and_principe: "Sao Tome and Principe",
    saudi_arabia: "Saudi Arabia",
    senegal: "Senegal",
    serbia: "Serbia",
    seychelles: "Seychelles",
    sierra_leone: "Sierra Leone",
    singapore: "Singapore",
    slovakia: "Slovakia",
    slovenia: "Slovenia",
    solomon_islands: "Solomon Islands",
    somalia: "Somalia",
    south_africa: "South Africa",
    south_sudan: "South Sudan",
    spain: "Spain",
    sri_lanka: "Sri Lanka",
    sudan: "Sudan",
    suriname: "Suriname",
    sweden: "Sweden",
    switzerland: "Switzerland",
    syria: "Syria",
    taiwan: "Taiwan",
    tajikistan: "Tajikistan",
    tanzania: "Tanzania",
    thailand: "Thailand",
    togo: "Togo",
    tonga: "Tonga",
    trinidad_and_tobago: "Trinidad and Tobago",
    tunisia: "Tunisia",
    turkey: "Turkey",
    turkmenistan: "Turkmenistan",
    tuvalu: "Tuvalu",
    uganda: "Uganda",
    ukraine: "Ukraine",
    united_arab_emirates: "United Arab Emirates",
    united_kingdom: "United Kingdom",
    united_states: "United States",
    uruguay: "Uruguay",
    uzbekistan: "Uzbekistan",
    vanuatu: "Vanuatu",
    vatican_city: "Vatican City",
    venezuela: "Venezuela",
    vietnam: "Vietnam",
    yemen: "Yemen",
    zambia: "Zambia",
    zimbabwe: "Zimbabwe"
};

export {
    OTB_ROLES,
    OTB_JOB_TITLES,
    OTB_COUNTRIES,
}